version: '3.9'

services:
  postgres:
    image: postgres:14.3-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: 'chi_test'
      POSTGRES_PASSWORD: 'chi_test'
      POSTGRES_DB: 'chi_test'
    volumes:
      - db:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

volumes:
  db: {}
